inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/test_data/*'
    - 'gon.gemspec'
Lint/HandleExceptions:
  AllowComments: true
Naming/AccessorMethodName:
  Exclude:
    - 'lib/gon/jbuilder/parser.rb'
